#!/bin/ansible-playbook

- hosts: localhost
  become: true
  tasks:
    - name: Check if the path of first run and second run are passed
      fail:
        msg: 'first_run and second_run should be passed using --extra-vars'
      when: first_run is not defined or second_run is not defined

    - name: Convert paths into absolute paths
      set_fact:
        first_run_abs: '{{ first_run|realpath }}'
        second_run_abs: '{{ second_run|realpath }}'

    - name: List all files in both runs
      find:
        paths: '{{ first_run_abs }}, {{ second_run_abs }}'
        recurse: true
        hidden: true
      register: items

    - name: Get unique relative paths
      set_fact:
        items: |
          {% set items_tmp = [] -%}
          {% for file in items.files -%}
            {% set dummy = items_tmp.append(file.path[first_run_abs|length + 1:] if file.path.startswith(first_run_abs) else file.path[second_run_abs|length + 1:]) -%}
          {%- endfor %}
          {{ items_tmp|unique }}

    - name: Find the difference between both runs
      include_tasks: ./file_diff.yml
      with_items: '{{ items }}'

    - debug:
        var: diff_dict
