---
- hosts: localhost
  become: true
  tasks:
    - name: Check if the path of first run and second run are passed
      fail:
        msg: "first_run and second_run should be passed using --extra-vars"
      when: first_run is not defined or second_run is not defined

    - name: Convert paths into absolute paths
      set_fact:
        first_run_abs: "{{ first_run|realpath }}"
        second_run_abs: "{{ second_run|realpath }}"
    
    - name: List all files in both runs
      find:
        paths: "{{ first_run_abs }}, {{ second_run_abs }}"
        recurse: true
        hidden: true
      register: files_list
    
    - name: Get unique relative paths
      set_fact:
        files_list: |
          {% set f_list = [] -%}
          {% for fl in files_list.files -%}
            {% set dump = f_list.append(fl.path[first_run_abs|length + 1:] if fl.path.startswith(first_run_abs) else fl.path[second_run_abs|length + 1:]) -%}
          {%- endfor %}
          {{ f_list|unique }}

    - name: Find the difference between two runs
      shell: "git diff --no-index {{ first_run_abs }}/{{ item }} {{ second_run_abs }}/{{ item }}; true"
      args:
        executable: /bin/bash
      with_items: "{{ files_list }}"
      register: file_diff
      
    - name: Find SElinux context of first run
      shell: "diff <(ls -lZ {{ first_run_abs }}/{{ item }} | awk '{ print $4 }') <(ls -lZ {{ second_run_abs }}/{{ item }} | awk '{ print $4 }'); true"
      args:
        executable: /bin/bash
      with_items: "{{ files_list }}"
      register: selinux_diff
   
    - name: Reindexing files difference
      set_fact:
        diff_dict: "{{ diff_dict | default({}) | combine(new_item, recursive=true) }}"
      vars:
        item_pre:
          - key: "{{ item.item }}"
            value: 
              file_diff: "{{ item.stdout_lines }}"          
        new_item: "{{ item_pre | items2dict }}"
      with_items: "{{ file_diff.results }}"
      no_log: true

    - name: Reindexing SElinux difference
      set_fact:
        diff_dict: "{{ diff_dict | default({}) | combine(new_item, recursive=true) }}"
      vars:
        item_pre:
          - key: "{{ item.item }}"
            value:
              selinux_diff: "{{ item.stdout_lines }}"
        new_item: "{{ item_pre | items2dict }}"
      with_items: "{{ selinux_diff.results }}"
      no_log: true

    - debug:
        var: diff_dict
